firstproject/urls.py
from django.contrib import admin
from django.urls import path, include
from level_five import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('firstapp/', include('firstapp.urls')),
    path('pro-two/', include('pro2.urls')),
    path('level-four/', include('level_four.urls')),
    path('level-five/', include('level_five.urls')),
]

level_five/urls.py
from django.urls import path
from level_five import views

app_name = 'level_five'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('special/',views.special, name='special'),
    path('login/', views.user_login, name='login'),
]

pro2/urls.py
from django.urls import path
from pro2 import views

urlpatterns = [
    path('', views.redirect_home, name='root_redirect'),
    path('sign-in/', views.sign_in_form, name='sign-in'),
    path('users/', views.index, name='index'),
    path('add-user/', views.add, name='add_user'),
]

level_five/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class UserProfileInfo(models.Model):
    """Adds additional profile info to django user class"""

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to="profile_pics", blank=True)

    def __str__(self):
        return self.user.username

level_five/forms.py
from django import forms
from django.contrib.auth.models import User
from level_five.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

level_five/views.py
from django.shortcuts import render
from level_five.forms import UserProfileInfoForm, UserForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'level_five/index.html')

@login_required
def special(request):
    return HttpResponse("YOU ARE LOGGED IN!!!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('level_five:index'))

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'level_five/registration.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})


def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('level_five:index'))

            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        
        else:
            print("Someone tried to login and failed!!")
            print("Username:{} and password {}".format(username, password))
            return HttpResponse("INVALID LOGIN DETAILS SUPPLIED")
    
    else:
        return render(request, 'level_five/login.html')

templates/level_five/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <title></title>
    </head>
    <body>
        <nav class='navbar navbar-default navbar-static-top'>
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">DJANGO</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    {% if user.is_authenticated %}
                        <li><a class="navbar-link" href="{% url 'level_five:logout' %}">Logout</a></li>
                    {% else %}
                        <li><a class="navbar-link" href="{% url 'level_five:login' %}">Login</a></li>
                    {% endif %}
                    <li><a class="navbar-link" href="{% url 'level_five:register' %}">Register</a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>
        
    </body>
</html>

templates/level_five/index.html
<!DOCTYPE html>
{% extends "level_five/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Django Level Five</h1>
</div>

{% endblock %}

templates/level_five/login.html
{% extends 'level_five/base.html' %}
{% block body_block %}

    <div class="jumbotron">
        <h1>Login</h1>
        <form action="{% url 'level_five:login' %}" method="POST">
            {% csrf_token %}
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Enter Username">
            <label for="password">Password:</label>
            <input type="password" name="password">
            <input type="submit" name="submit" value="Login">
        </form>
    </div>

{% endblock %}

templates/level_five/registration.html
{% extends 'level_five/base.html' %}
{% load staticfiles %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Thank You for registering!</h1>
    {% else %}
        <h1>Register Here!</h1>
        <h3>Fill out this form: </h3>

        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" name="submit" value="Register">
        </form>
    {% endif %}
</div>
{% endblock %}