firstproject/urls.py
from django.contrib import admin
from django.urls import path, include
from level_five import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('firstapp/', include('firstapp.urls')),
    path('pro-two/', include('pro2.urls')),
    path('level-four/', include('level_four.urls')),
    path('level-five/', include('level_five.urls')),
]

level_four/urls.py
from django.urls import path
from level_four import views

#TEMPLATE TAGGING
app_name = 'level-four'

urlpatterns = [
    path('', views.index, name='index'),
    path('relative/', views.relative, name='relative'),
    path('other/', views.other, name='other'),
]

pro2/urls.py
from django.urls import path
from pro2 import views

urlpatterns = [
    path('', views.redirect_home, name='root_redirect'),
    path('sign-in/', views.sign_in_form, name='sign-in'),
    path('users/', views.index, name='index'),
    path('add-user/', views.add, name='add_user'),
]

level_four/models.py
from django.db import models

# Create your models here.

level_four/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text':'hello world', 'number':100}
    return render(request,'level_four/index.html', context_dict)

def other(request):
    return render(request, 'level_four/other.html')

def relative(request):
    return render(request, 'level_four/rel_url_templates.html')

templates/level_four/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name='viewport' content="width=device-width initial-scale=1.0">
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'level-four:index' %}">BRAND</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'level-four:other' %}">Other</a></li>
                </ul>
            </div>
        </nav>

        <div class="container">
            {% block body_block %}
            {% endblock %}
        </div>

    </body>
</html>

templates/level_four/index.html
<!DOCTYPE html>
{% extends "level_four/base.html" %}
{% load my_extras %}
{% block body_block %}
        <h1>Welcome to index</h1>
        {{ text|cutt:"hello"  }}
        {{ number|add:"99" }}
        {% endblock %}

templates/level_four/other.html
<!DOCTYPE html>
{% extends "level_four/base.html" %}
{% block body_block %}
        <h1>Welcome to other</h1>
        <h3>This is an example of template inheritance</h3>
        {% endblock %}

templates/level_four/rel_url_templates.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <h1>Welcome to rel_url_templates</h1>
        <a href="{% url 'level-four:other' %}">The other page</a>
        <a href="{% url 'admin:index' %}">Admin</a>
    </body>
</html>